version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  chatclub.web:
    image: chatclubweb:0.1
    ports:
      - "8001:80"
    build:
      context: .
      dockerfile: src/ChatClub.Web/Dockerfile
    networks:
      - dockerapi-dev

  chatclubbot:
    image: chatclubbot:0.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
    build:
      context: .
      dockerfile: src/ChatClub.Bot/Dockerfile
    networks:
      - dockerapi-dev

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    networks:
      - dockerapi-dev

  rabbitmq: 
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dockerapi-dev